from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, ReplyKeyboardRemove


btnMain = KeyboardButton('Главное меню')

#------------------Main Menu----------------------------
btn_apple = KeyboardButton('Apple')
btn_android = KeyboardButton('Android')
btn_laptop = KeyboardButton('Ноутбук')
btn_pc = KeyboardButton('Компьютер')
btn_game = KeyboardButton('Игровая консоль')
Menupro = KeyboardButton('Меню')
mainMenu = ReplyKeyboardMarkup(resize_keyboard=True ).add(btn_apple, btn_android, btn_laptop, btn_pc, btn_game, Menupro)
#------------------Apple Menu----------------------------
btn_iPhone = KeyboardButton('iPhone')
btn_iPad = KeyboardButton('iPad')
btn_Macbook = KeyboardButton('MacBook')
btn_Apple_watch = KeyboardButton('Apple Watch')
btn_iMac = KeyboardButton('iMac')
apple_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_iPhone, btn_iPad, btn_Macbook, btn_Apple_watch, btn_iMac, btnMain)
#-----------------Android Menu--------------------------
btn_samsung = KeyboardButton('Samsung')
btn_xiaomi = KeyboardButton('Xiaomi')
btn_honor = KeyboardButton('Honor')
btn_huawei = KeyboardButton('Huawei')
btn_realme = KeyboardButton('Realme')
android_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_samsung, btn_xiaomi, btn_honor, btn_huawei, btn_realme)
#-----------------Laptop Menu---------------------------
btn_clean = KeyboardButton('Чистка от пыли с заменой термопасты')
btn_water = KeyboardButton('Пролили воду')
btn_lcd = KeyboardButton('Нет изображения')
btn_kd = KeyboardButton('Не работает клавиатура')
btn_power = KeyboardButton('Не включается')
btn_adapter = KeyboardButton('Не заряжается')
laptop_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_clean, btn_water, btn_lcd, btn_kd, btn_power, btn_adapter)
#-----------------PC Menu--------------------------------
btn_cleanpc = KeyboardButton('Чистка от пыли с заменой термопасты')
btn_lcdpc = KeyboardButton('Нет изображения')
btn_powerpc = KeyboardButton('Не включается')
pc_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_cleanpc, btn_lcdpc, btn_powerpc)
#-----------------ID Menu---------------------------
btn_faceid = KeyboardButton('Face ID')
btn_touchid = KeyboardButton('Touch ID')
id_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_faceid, btn_touchid)
#-------------------Touch Menu ------------------------ 
ip8 = KeyboardButton('iPhone 8')
ipse2 = KeyboardButton('iPhone SE 2020')
ipse3 = KeyboardButton('iPhone SE 2022')
ip8p = KeyboardButton('iPhone 8 Plus')
touch_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(ip8, ipse2, ipse3, ip8p)
#---------------- Face menu ------------------
ipx = KeyboardButton('iPhone X')
ipxr = KeyboardButton('iPhone Xr')
ipxs = KeyboardButton('iPhone XS')
ipxsm = KeyboardButton('iPhone Xs Max')
ip11 = KeyboardButton('iPhone 11')
ip11p = KeyboardButton('iPhone 11 Pro')
ip11pm = KeyboardButton('iPhone 11 Pro Max')
ip12 = KeyboardButton('iPhone 12')
ip12p = KeyboardButton('iPhone 12 Pro')
ip12pm = KeyboardButton('iPhone 12 Pro Max')
ip13 = KeyboardButton('iPhone 13')
ip13p = KeyboardButton('iPhone 13 Pro')
ip13pm = KeyboardButton('iPhone 13 Pro max')
ip14 = KeyboardButton('iPhone 14')
ip14pp = KeyboardButton('iPhone 14 Plus')
ip14p = KeyboardButton('iPhone 14 Pro')
ip14pm = KeyboardButton('iPhone 14 Pro Max ')
face_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(ipx, ipxr, ipxs, ip11, ip11p, ip11pm, ip12, ip12p, ip12pm, ip13, ip13p, ip13pm, ip14, ip14pp, ip14p, ip14pm)
#----- Repair Samsung --------
s_lcd = KeyboardButton('Разбит дисплей')
s_batt = KeyboardButton('Заменить Аккумулятор')
s_off = KeyboardButton('Не включается')
s_charg = KeyboardButton('Не заряжается')
s_water = KeyboardButton('Пролили воду')
sam_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(s_lcd, s_batt, s_off, s_charg, s_water)
#----- Repair Xiaomi -------
x_lcd = KeyboardButton('Разбит дисплей')
x_batt = KeyboardButton('Заменить Аккумулятор')
x_off = KeyboardButton('Не включается')
x_charg = KeyboardButton('Не заряжается')
x_water = KeyboardButton('Пролили воду')
xia_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(x_lcd, x_batt, x_off, x_charg, x_water)
#------ Repair Honor ------
ho_lcd = KeyboardButton('Разбит дисплей')
ho_batt = KeyboardButton('Заменить Аккумулятор')
ho_off = KeyboardButton('Не включается')
ho_charg = KeyboardButton('Не заряжается')
ho_water = KeyboardButton('Пролили воду')
hon_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(ho_lcd, ho_batt, ho_off, ho_charg, ho_water)
#------- Repair Huawei --------
hu_lcd = KeyboardButton('Разбит дисплей')
hu_batt = KeyboardButton('Заменить Аккумулятор')
hu_off = KeyboardButton('Не включается')
hu_charg = KeyboardButton('Не заряжается')
hu_water = KeyboardButton('Пролили воду')
hua_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(hu_lcd, hu_batt, hu_off, hu_charg, hu_water)
#-------- Repair Realme --------
r_lcd = KeyboardButton('Разбит дисплей')
r_batt = KeyboardButton('Заменить Аккумулятор')
r_off = KeyboardButton('Не включается')
r_charg = KeyboardButton('Не заряжается')
r_water = KeyboardButton('Пролили воду')
rea_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(r_lcd, r_batt, r_off, r_charg, r_water)
#------- Repair iPhone -------
i_lcd = KeyboardButton('Разбит дисплей')
i_batt = KeyboardButton('Заменить Аккумулятор')
i_off = KeyboardButton('Не включается')
i_charg = KeyboardButton('Не заряжается')
i_water = KeyboardButton('Пролили воду')
i_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(i_lcd, i_batt, i_off, i_charg, i_water)
#------ Repair Console ------
sx_clean = KeyboardButton('Чистка от пыли')
sx_lcd = KeyboardButton('Нет изображения')
sx_rom = KeyboardButton('Прошить')
sx_pow = KeyboardButton('Не включается')
sx_menu =  ReplyKeyboardMarkup(resize_keyboard=True).add(sx_clean, sx_lcd, sx_rom, sx_pow)
#----- Menu Console -------